// Generated by Copilot
import Logo from "@/components/common/Logo";
import NavLinks from "./NavLinks";
import MobileMenu from "./MobileMenu";
import ThemeToggle from "@/components/common/ThemeToggle";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { MessageSquareMoreIcon } from "lucide-react";

const Header = () => {
  return (
    <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      <div className="container flex h-16 items-center justify-between">
        {/* Logo Section */}
        <div className="flex items-center">
          <Logo />
        </div>

        {/* Navigation Section */}
        <div className="flex items-center gap-6 lg:gap-8">
          {/* Desktop Navigation */}
          <NavLinks className="hidden lg:flex" />

          {/* Action Buttons */}
          <div className="flex items-center gap-3">
            <ThemeToggle />

            <Button className="hidden lg:inline-flex" size="lg" asChild>
              <Link href="#kontak">
                <MessageSquareMoreIcon className="size-5" />
                Pesan Sekarang
              </Link>
            </Button>
          </div>

          {/* Mobile Menu */}
          <MobileMenu />
        </div>
      </div>
    </header>
  );
};
export default Header;
